Algoritmo "consumo"



Var
    distancia : real
    CombustivelGasto : real
    ConsumoMedio : real

Inicio
       escreval("Distancia percorrida:")
       leia(distancia)
       escreval("Combustível gasto:")
       leia(CombustivelGasto)
       
       ConsumoMedio <- distancia / CombustivelGasto
       
       escreval("Consumo medio =", ConsumoMedio)
       







Fimalgoritmo