Algoritmo "notas"

Var
     nota1 : real
     nota2 : real
     notaf : real

Inicio
      escreval("Digite a primeira nota:")
      leia(nota1)
      escreval("Digite a segunda nota:")
      leia(nota2)
      
      notaf <- nota1 + nota2
      
      escreval("NOTA FINAL =", notaf)
      
      se notaf < 60 entao
        escreval("REPROVADO")
      fimse









Fimalgoritmo