Algoritmo "Troco"

Var

       Preco : real
       Quantidade : Inteiro
       DinheiroRecebido : inteiro
       troco : Real


Inicio

       escreval("Preço unitário do produto:")
       leia(Preco)
       escreval("Quantidade comprada:")
       leia(Quantidade)
       escreval("Dinheiro recebido:")
       leia(DinheiroRecebido)
       
       troco <- DinheiroRecebido - Preco * Quantidade
       
       escreval("Troco:", troco)







Fimalgoritmo